### ISSUE TITLE
Problem with deploy and .env

### ISSUE THREAD

**Issue by jsanchezwingsoft** [santthosh/assistants-hub#26]
Hello, can you give me an example of the .env that must be deployed and the step by step of the local deploy, so I can see if I can dockerize the project. Can anything else be used with OpenAI and what would the procedure be? @santthosh

**Comment by santthosh** [comment]
@jsanchezwingsoft Thank you for pointing this out. There are some blockers running this locally. Will use this ticket to resolve these issues

- [x] Added [`.env.template`](https://github.com/Assistants-Hub/assistantshub.ai/blob/main/.env.template) to provide examples of local .env file that is necessary 
- [x] Ability to use Username / Password from the database instead of Google or Github auth - A way to selectively enable them as necessary
- [ ] Ability to selectively enable or disable ModelProviders (OpenAI / Google) 
- [ ] Blob read write store from Vercel is necessary for uploading documents, we need a better alternative for running this locally or make an adapter to use S3 or other storage providers

**Comment by jsanchezwingsoft** [comment]
Good morning, thank you very much for responding, I can help you with point number 4 about the S3 blob, you can use an S3 Minio container (https://min.io/) I always use it in docker and so far it has worked very well. well and it's open source. greetings. @santthosh

**Comment by santthosh** [comment]
This is awesome @jsanchezwingsoft, Will focus and get you unblocked ASAP so you can help us dockerize this

**Comment by jsanchezwingsoft** [comment]
[like]  Jonathan Sanchez reacted to your message:
________________________________

**Comment by santthosh** [comment]
@jsanchezwingsoft with the latest updates you can now login to local with temporary credentials configured in the `.env` file . Below is the configuration in the `.env` that you would use to login and try out all the functionality

```
# Providers
ENABLE_CREDENTIALS_PROVIDER=true
ENABLE_EMAIL_PROVIDER=false
ENABLE_GITHUB_PROVIDER=false
ENABLE_GOOGLE_PROVIDER=false

# Credentials Provider Parameters
CREDENTIALS_APPROVED_USERNAME=jsmith
CREDENTIALS_APPROVED_PASSWORD=localhost@
```

Vercel Blob store variable or ModelProvider enablement should not affect you right now for containerization. But will open issues for these and update this thread. 

You should be unblocked now

<img width="793" alt="Screenshot 2024-04-24 at 4 49 17 PM" src="https://github.com/Assistants-Hub/assistantshub.ai/assets/2665127/a975aad1-a723-4be5-af34-b086899f842e">

**Comment by santthosh** [comment]
Added #34, #33 to address the gaps for future

Added #35 to help track the containerization efforts. Thank you @jsanchezwingsoft
